sudo: required
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - git config --local user.name $GIT_USER
  - git config --local user.email "triple0zero@gmail.com"
  - export VERSION='0.0.2'
  - export TRAVIS_TAG=$VERSION-$TRAVIS_BUILD_NUMBER
  - git tag $TRAVIS_TAG
  - git push --tags
script:
  - docker build -t dream20200716/test:$VERSION-$TRAVIS_BUILD_NUMBER -t dream20200716/test:latest .
  - docker push dream20200716/test:${VERSION}-$TRAVIS_BUILD_NUMBER
  - docker push dream20200716/test:latest
  - docker logout
#  - if [ $TRAVIS_BRANCH = "develop" ]; then echo "DEV deploy"; fi
#  - if [ $TRAVIS_BRANCH = "master" ]; then docker ps -a; fi
